# avoid in production, instead connect to external running mongo service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      containers:
      - name: mailer-service
        image: 'miq84/mail-service:1.0.0'
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MAIL_DOMAIN
            value: "localhost"
          - name: MAIL_HOST
            value: "mailhog"
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: FROM_NAME
            value: "John Smith"
          - name: FROM_ADDRESS
            value: "admin@example.com" 

        ports:
          - containerPort: 27017

--- 

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      name: main-port
      port: 27017
      targetPort: 27017